/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GithubRequestBuilderRequestsMetadata, type GithubRequestBuilder } from './github/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /callback/login
 */
export interface LoginRequestBuilder extends BaseRequestBuilder<LoginRequestBuilder> {
    /**
     * The github property
     */
    get github(): GithubRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const LoginRequestBuilderUriTemplate = "{+baseurl}/callback/login";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LoginRequestBuilderNavigationMetadata: Record<Exclude<keyof LoginRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    github: {
        requestsMetadata: GithubRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
