/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HackOManiaApiEndpointsAuthWhoAmIResponse}
 */
// @ts-ignore
export function createHackOManiaApiEndpointsAuthWhoAmIResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHackOManiaApiEndpointsAuthWhoAmIResponse;
}
/**
 * The deserialization information for the current model
 * @param HackOManiaApiEndpointsAuthWhoAmIResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHackOManiaApiEndpointsAuthWhoAmIResponse(hackOManiaApiEndpointsAuthWhoAmIResponse: Partial<HackOManiaApiEndpointsAuthWhoAmIResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "gitHubId": n => { hackOManiaApiEndpointsAuthWhoAmIResponse.gitHubId = n.getNumberValue(); },
        "gitHubLogin": n => { hackOManiaApiEndpointsAuthWhoAmIResponse.gitHubLogin = n.getStringValue(); },
    }
}
export interface HackOManiaApiEndpointsAuthWhoAmIResponse extends Parsable {
    /**
     * The gitHubId property
     */
    gitHubId?: number | null;
    /**
     * The gitHubLogin property
     */
    gitHubLogin?: string | null;
}
/**
 * Serializes information the current object
 * @param HackOManiaApiEndpointsAuthWhoAmIResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHackOManiaApiEndpointsAuthWhoAmIResponse(writer: SerializationWriter, hackOManiaApiEndpointsAuthWhoAmIResponse: Partial<HackOManiaApiEndpointsAuthWhoAmIResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!hackOManiaApiEndpointsAuthWhoAmIResponse || isSerializingDerivedType) { return; }
    writer.writeNumberValue("gitHubId", hackOManiaApiEndpointsAuthWhoAmIResponse.gitHubId);
    writer.writeStringValue("gitHubLogin", hackOManiaApiEndpointsAuthWhoAmIResponse.gitHubLogin);
}
/* tslint:enable */
/* eslint-enable */
