/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { LoginRequestBuilderNavigationMetadata, type LoginRequestBuilder } from './login/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /callback
 */
export interface CallbackRequestBuilder extends BaseRequestBuilder<CallbackRequestBuilder> {
    /**
     * The login property
     */
    get login(): LoginRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CallbackRequestBuilderUriTemplate = "{+baseurl}/callback";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CallbackRequestBuilderNavigationMetadata: Record<Exclude<keyof CallbackRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    login: {
        navigationMetadata: LoginRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
